### PR TITLE
Fixes for PVS 8.0

### PR DESCRIPTION
**Pull request by samowre**

### CODE REVIEW

**Comment by kai-e** [comment]
Not sure anyone cares, but this works for me.

**Comment by marianomoscato** [comment]
Thanks for the feedback, Kai! 

I'm finding some issues when rerunning these proofs on an Intel Mac (PVS 8.0). Just to double check, did you run prove-all (or something similar) on the whole library?

**Comment by kai-e** [comment]
Good point. I hadn't tried `prove-all`. That shows issues indeed. The batch of `*** Warning: Library <foo> is out of order. It should appear before <bar> in nasalib.all` is expected, but then there's a
```console
<foo>                     Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (<foo>)
```
for every sub-library. That smells like the SBCL ALL CAPS issue again.

Entire output:
```console
√ ~/src/pvs_nasalib/nasalib % ./prove-all                               5:17:00
Working on libraries file: nasalib.all.

ints                     Cleaning... [OK]
structures               Cleaning... [OK]
reals                    Cleaning... [OK]
*** Warning: Library lnexp is out of order. It should appear before reals in nasalib.all
*** Warning: Library extended_nnreal is out of order. It should appear before reals in nasalib.all
*** Warning: Library analysis is out of order. It should appear before reals in nasalib.all
*** Warning: Library series is out of order. It should appear before reals in nasalib.all
*** Warning: Library sigma_set is out of order. It should appear before reals in nasalib.all
*** Warning: Library power is out of order. It should appear before reals in nasalib.all
*** Warning: Library measure_integration is out of order. It should appear before reals in nasalib.all
*** Warning: Library topology is out of order. It should appear before reals in nasalib.all
*** Warning: Library orders is out of order. It should appear before reals in nasalib.all
*** Warning: Library sets_aux is out of order. It should appear before reals in nasalib.all
*** Warning: Library metric_space is out of order. It should appear before reals in nasalib.all
*** Warning: Library lebesgue is out of order. It should appear before reals in nasalib.all
orders                   Cleaning... [OK]
analysis                 Cleaning... [OK]
sets_aux                 Cleaning... [OK]
numbers                  Cleaning... [OK]
series                   Cleaning... [OK]
trig                     Cleaning... [OK]
vectors                  Cleaning... [OK]
sigma_set                Cleaning... [OK]
algebra                  Cleaning... [OK]
vect_analysis            Cleaning... [OK]
lnexp                    Cleaning... [OK]
power                    Cleaning... [OK]
interval_arith           Cleaning... [OK]
affine_arith             Cleaning... [OK]
matrices                 Cleaning... [OK]
Bernstein                Cleaning... [OK]
Sturm                    Cleaning... [OK]
Tarski                   Cleaning... [OK]
MetiTarski               Cleaning... [OK]
fast_approx              Cleaning... [OK]
shapes                   Cleaning... [OK]
complex                  Cleaning... [OK]
digraphs                 Cleaning... [OK]
float/axm_bnd            Cleaning... [OK]
float/fnd_bnd            Cleaning... [OK]
float/fnd_unb            Cleaning... [OK]
float/ieee854            Cleaning... [OK]
fault_tolerance     Cleaning... [OK]
graphs                   Cleaning... [OK]
PVSioChecker             Cleaning... [OK]
LTL                      Cleaning... [OK]
exact_real_arith     Cleaning... [OK]
aviation                 Cleaning... [OK]
ACCoRD                   Cleaning... [OK]
sorting                  Cleaning... [OK]
TRS                      Cleaning... [OK]
CCG                      Cleaning... [OK]
PVS0                     Cleaning... [OK]
Riemann                  Cleaning... [OK]
examples                 Cleaning... [OK]
topology                 Cleaning... [OK]
complex_alt              Cleaning... [OK]
scott                    Cleaning... [OK]
while                    Cleaning... [OK]
extended_nnreal     Cleaning... [OK]
metric_space             Cleaning... [OK]
measure_integration     Cleaning... [OK]
complex_integration     Cleaning... [OK]
lebesgue                 Cleaning... [OK]
probability              Cleaning... [OK]
co_structures            Cleaning... [OK]
TU_Games                 Cleaning... [OK]
linear_algebra           Cleaning... [OK]
ASP                      Cleaning... [OK]
line_segments            Cleaning... [OK]
polygons                 Cleaning... [OK]
polygon_merge            Cleaning... [OK]
mv_analysis              Cleaning... [OK]
ODEs                     Cleaning... [OK]
dL                       Cleaning... [OK]
mult_poly                Cleaning... [OK]

*** Number of libraries: 64
Working on libraries file: nasalib.all.
Cleaning PVS_LIBRARY_PATH variable.
Adding /Users/kaie/src/pvs_nasalib/nasalib to PVS_LIBRARY_PATH.

ints                     Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (ints)
structures               Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (structures)
reals                    Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (reals)
*** Warning: Library lnexp is out of order. It should appear before reals in nasalib.all
*** Warning: Library extended_nnreal is out of order. It should appear before reals in nasalib.all
*** Warning: Library analysis is out of order. It should appear before reals in nasalib.all
*** Warning: Library series is out of order. It should appear before reals in nasalib.all
*** Warning: Library sigma_set is out of order. It should appear before reals in nasalib.all
*** Warning: Library power is out of order. It should appear before reals in nasalib.all
*** Warning: Library measure_integration is out of order. It should appear before reals in nasalib.all
*** Warning: Library topology is out of order. It should appear before reals in nasalib.all
*** Warning: Library orders is out of order. It should appear before reals in nasalib.all
*** Warning: Library sets_aux is out of order. It should appear before reals in nasalib.all
*** Warning: Library metric_space is out of order. It should appear before reals in nasalib.all
*** Warning: Library lebesgue is out of order. It should appear before reals in nasalib.all
orders                   Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (orders)
analysis                 Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (analysis)
sets_aux                 Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (sets_aux)
numbers                  Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (numbers)
series                   Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (series)
trig                     Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (trig)
vectors                  Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (vectors)
sigma_set                Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (sigma_set)
algebra                  Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (algebra)
vect_analysis            Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (vect_analysis)
lnexp                    Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (lnexp)
power                    Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (power)
interval_arith           Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (interval_arith)
affine_arith             Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (affine_arith)
matrices                 Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (matrices)
Bernstein                Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (Bernstein)
Sturm                    Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (Sturm)
Tarski                   Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (Tarski)
MetiTarski               Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (MetiTarski)
fast_approx              Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (fast_approx)
shapes                   Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (shapes)
complex                  Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (complex)
digraphs                 Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (digraphs)
float/axm_bnd            Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (float/axm_bnd)
*** Warning: File float/axm_bnd/pvsbin/top.dep not found.
float/fnd_bnd            Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (float/fnd_bnd)
*** Warning: File float/fnd_bnd/pvsbin/top.dep not found.
float/fnd_unb            Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (float/fnd_unb)
*** Warning: File float/fnd_unb/pvsbin/top.dep not found.
float/ieee854            Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (float/ieee854)
*** Warning: File float/ieee854/pvsbin/top.dep not found.
fault_tolerance     Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (fault_tolerance)
graphs                   Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (graphs)
PVSioChecker             Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (PVSioChecker)
LTL                      Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (LTL)
exact_real_arith     Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (exact_real_arith)
aviation                 Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (aviation)
ACCoRD                   Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (ACCoRD)
sorting                  Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (sorting)
TRS                      Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (TRS)
CCG                      Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (CCG)
PVS0                     Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (PVS0)
Riemann                  Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (Riemann)
examples                 Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (examples)
topology                 Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (topology)
complex_alt              Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (complex_alt)
scott                    Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (scott)
while                    Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (while)
extended_nnreal     Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (extended_nnreal)
metric_space             Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (metric_space)
measure_integration     Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (measure_integration)
complex_integration     Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (complex_integration)
lebesgue                 Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (lebesgue)
probability              Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (probability)
co_structures            Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (co_structures)
TU_Games                 Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (TU_Games)
linear_algebra           Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (linear_algebra)
ASP                      Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (ASP)
line_segments            Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (line_segments)
polygons                 Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (polygons)
polygon_merge            Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (polygon_merge)
mv_analysis              Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (mv_analysis)
ODEs                     Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (ODEs)
dL                       Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (dL)
mult_poly                Proving... [FAIL]
*** Error: The value          METIT        is not of type          STRING (mult_poly)

*** Number of libraries: 64
*** Grand Totals: 0 proofs / 0 formulas. Missed: 0 formulas.
```

**Comment by marianomoscato** [comment]
Thanks for trying this out. This issue relates to how the Extrategies module returns the names of the available Oracles and what prove-all expects. I'm working on a fix for this. I'll let you know when it's ready.

**Comment by kai-e** [comment]
I'm making progress with 2 tiny changes (after I installed MetiTarski from sources because I'm on ARM). 
1. in line 363 of `MetiTarski/metit.lisp` inject `--z3` (I could not get metit even outside PVS past Errors without that flag even though z3 is the default oracle.)
2. omit the `--disable-oracles` flag. I removed it from line 5 in `nasalib.all` to run a little test to exercise metit and prove-all:
```console
$ ../provethem --before=digraphs --after=Sturm nasalib.all
Working on libraries file: nasalib.all.

Tarski                   Proving... [OK]
MetiTarski               Proving... [OK]
fast_approx              Proving... [OK]
shapes                   Proving... [OK]
complex                  Proving... [MISS]
*** Warning: Missed 8 formulas.

*** Number of libraries: 5
*** Grand Totals: 1090 proofs / 1098 formulas. Missed: 8 formulas.
```
I don't know yet why some lemmas failed to prove in `complex` and there surely is a more principled way to fix the issue with oracles but this looks like a bit of progress.

**Comment by cesaramh** [comment]
We added an experimental v8.0 branch with the most recent update to nasalib for the current development version of PVS.

**Pull request closed without merging**
