### PR TITLE
Di topological sort

### PR DESCRIPTION
**Pull request by clementblaudeau**
This PR adds a topological sort to the `digraph` library, defined on **computable** acyclic digraphs. A couple of changes have been made to split the `paths.pvs` and `dag.pvs` for the two definitions of digraphs. The main theory `c_topological_sort` revolves around a `visit` function that does a *depth-first* search of the graph, using a marking system (none, temporary, permanent)

### CODE REVIEW

**Comment by clementblaudeau** [comment]
G1_test
The following test has been made in the `c_topological_sort_example` theory with PVSIO.

**Comment by cesaramh** [comment]
Hi Clement. Thanks for your contribution. I'm type-checking it in PVS-7.1 in my installations (Aquamacs/Allegro/Mac OSX and Emacs/Allegro/Linux), and in both cases PVS reports a syntax error in the line 106 of c_topological_sort.pvs (over m'). The error is: invalid id:
	                                  
 topperm_list(G, m')(l') ∧ greater_marking(m', m) ∧ suffix?(l, l') ∧ permanent?(m'(node)) ∧ ...

I changed the "primed ids", e.g., mp instead of m', lp instead of l', adjsp instead of adjs', and the theory proves. 

I'm curious about the version you used to type-check this contribution. We generally don't use PVS with non-ASCII characters as I don't know how good is the support in different editors. Do you mind changing the primed IDs to non-primed ones?

Also, the following TCCs appear to be broken when using prove-all -do digraphs:

Processing digraphs. Writing output to file summaries/digraphs.summary
Logging PVS information in summaries/digraphs.log
 Proof summary for theory c_digraphs_def
    edges_set_to_list_for_TCC5............unfinished          [shostak](0.00 s)
    Theory totals: 59 formulas, 59 attempted, 58 succeeded (25.05 s)
 Proof summary for theory c_topological_sort
    visit_TCC20...........................unfinished          [shostak](4.90 s)
    Theory totals: 58 formulas, 58 attempted, 57 succeeded (69.16 s)
Grand Totals: 741 proofs, 741 attempted, 739 succeeded (637.61 s)


Best Regards and Happy Holidays,

Cesar

**Comment by clementblaudeau** [comment]
Hi Cesar, 
Thank you for the feedback ! 
I've removed all primes in variables names, as well as the unicode symbols for `forall`, `exists`, `not` and `lambda` that I was using. I'm also on PVS 7.1 with Emacs on Linux, but I use recent snapshots that may have an extended support for unicode or a slightly more powerful `(assert)` command. It might explain why `edges_set_to_list_for_TCC5`'s proof is broken, while it's working for my version. I can push a proof of it where `(grind)` is called instead of `(assert)` at the end, just in case ?
I've also corrected TCCs that were making explicit instantiation of primed IDs.

**Comment by cesaramh** [comment]
Clement,
I made additional modifications because some proofs needed repair after the renaming.  I'm rerunning all the nasalib proofs to make sure there are no dependencies I'm missing. Do you mind if I push my commit instead of the pull request? I'll acknowledge your contribution in the README file.

Thanks,
Cesar

**Comment by clementblaudeau** [comment]
Thank you for repairing the proofs.
You can push the changes in any way that is best for you. You also have full edit rights on this PR if you want to commit here before merging. Tell me if I can be of any help!

**Comment by cesaramh** [comment]
I pushed your contribution after minor changes. Thanks again.

**Pull request closed without merging**
